
export const FETCH_PATIENTS = 'FETCH_PATIENTS';
export const CREATE_PATIENT = 'CREATE_PATIENT';
export const FETCH_PATIENT = 'FETCH_PATIENT';

export const CREATE_DIAGNOSTIC = 'CREATE_DIAGNOSTIC';
export const UPDATE_DIAGNOSTIC = 'UPDATE_DIAGNOSTIC';